### ISSUE TITLE
怎么升级到10.15？直接升级失败了

### ISSUE THREAD

**Issue by xiaominglei001** [kkzzhizhou/S200H_I7-8750H_Hackintosh#10]
目前情况
```
系统10.14.4, cpu 8750h ，英睿达2666 8g ，ssd intel 760p ，无线网卡和蓝牙都是买时自带的，不用
```
目前用的EFI是这个，我想升级到10.15，直接升级不行，会出现一个圆圈加个斜杠，问下怎么办

**Comment by xiaominglei001** [comment]
目前情况
```
系统10.14.4, cpu 8750h ，英睿达2666 8g ，ssd intel 760p ，无线网卡和蓝牙都是买时自带的，不用
```
目前用的EFI是这个，我想升级到10.15，直接升级不行，会出现一个圆圈加个斜杠，问下怎么办，直接用你和这个EFI文件替换我现在的系统EFI然后再appstore升级系统就可以吗

**Comment by xiaominglei001** [comment]
已用上10.15，直接更新会出现圆圈和斜杠那个图标，我的步骤，黑果小兵上下载10.15系统，然后用balenaEtcher刻录好u盘，然后挂载这个u盘下的EFI分区，删除这个分区里的所有文件，然后去找到@EngLearnsh 的s200h项目，下载他的EFI文件，全部拷贝到刚才刻录u盘的EFI分区里，然后正常安装就可以了。

**Comment by dadaobixing** [comment]
@你好，我按照你这个方式操作，制作黑果小兵的U盘，替换为 @EngLearnsh 的EFI。根本就不能引导进安装界面，卡在苹果loading的界面，请问是怎么回事。

**Comment by EngLearnsh** [comment]
>  @你好，我按照你这个方式操作，制作黑果小兵的U盘，替换为 @EngLearnsh 的EFI。根本就不能引导进安装界面，卡在苹果loading的界面，请问是怎么回事。

你好，能否用-v然后看看卡在哪儿，过几天我会更新一下efi

**Comment by dadaobixing** [comment]
> > @你好，我按照你这个方式操作，制作黑果小兵的U盘，替换为 @EngLearnsh 的EFI。根本就不能引导进安装界面，卡在苹果loading的界面，请问是怎么回事。
> 
> 你好，能否用-v然后看看卡在哪儿，过几天我会更新一下efi

你好，卡在apfs_module_start：1689：load com.apple.filesystems.apfs这一行。
参考别人的教程放进去SSDT-EC这个文件，又卡在了SMCSuperIO  ssio failed to detect supported superIO chip
