### ISSUE TITLE
睡眠唤醒后Chrome等问题解决了吗

### ISSUE THREAD

**Issue by cxlanyagege** [kkzzhizhou/S200H_I7-8750H_Hackintosh#6]
有没有可能是PXSX的问题？自己买的i9也有这个问题

**Comment by EngLearnsh** [comment]
之前用的hdmi连接，现在换了mdp好像没问题了

**Comment by frankhefeng** [comment]
跟睡眠似乎无关。昨天碰到：开了好几个tab看视频，其中两个tab的视频始终加载不出来，其他的tab没问题。那两个tab刷新也不行，把tab关了，重新打开同一个URL也不行。而且此时，Quicktime播放 本机 Mp4文件也不行，卡住，iina一样。
如果关掉Chrome，会发现无法完全退出，任务管理器里面有个进程，强制杀掉后，再开Chrome，会出现白屏，Chrome的窗口，只剩下 放大缩小等三个按钮，其他全部白色的。

所以，看起来是 视频的解码器 进入了某种奇怪的状态，也许跟视频文件本身有关。

以上现象在使用过程中随机发生，只有重启才能解决。

vscode 有时候也会有类似Chrome的情况发生，就是，失去响应，也无法关掉。

**Comment by cxlanyagege** [comment]
这情况看来和直接睡眠然后唤醒后的情况一摸一样，也不知道是怎么触发的，看log也没看出什么。对了，你是用HDMI还是mDP，我看tonymac上有几个人也买了一样的机器，mDP的没问题，HDMI却有种情况

**Comment by frankhefeng** [comment]
我接了两个显示器。
每次开机。 HDMI 上的显示器没问题，mDP上的显示器，没显示
mDP 显示器我是竖着的。不知道有没有关系。晚点试一下。

每次开机我得首先 卡在 Clover 3分钟，进入系统后，进显示器设置，折腾一番。才能正常使用

**Comment by cxlanyagege** [comment]
我之前cs关闭的时候clover界面也很卡，然后系统装完后我就把clover鼠标关掉就不卡了，然后之前mojave开机时间也很长，升级完catalina后开机现在才8秒

**Comment by frankhefeng** [comment]
cs关闭 是指？  clover鼠标怎么关呢？
我还在mojave。

**Comment by cxlanyagege** [comment]
少打了一个m。。。是csm，bios里倒数第二页里面倒数第一个选项，打开，然后clover应该就不卡了。我为了与原生mac的bios设置相对靠近，所以把clover里面鼠标支持关掉了（config.plist里有个key叫mouse，disable就可以了），这样再把csm关掉，clover也不会卡了

**Comment by frankhefeng** [comment]
感谢 @EngLearnsh 的确开启CSM后 Clover不卡了。然后我的双显示器问题也与CSM 里面的 Video设置有关。

设置为：UEFI，那么 进入Mac之后， mDP显示器就进入休眠模式
设置为：Legacy，插双显示器则无法开机，显示器无输出。只插HDMI进入Clover之后插上mDP则两个显示器都可以认出。
设置为：Do not launch，则显示器无输出。最后拔了小电池才重新进去。

看来 Video=UEFI 是唯一选择。

**Comment by frankhefeng** [comment]
对了，config.plist 里面我设置了 mouse disable, 但是如果 CSM 关了，还是会clover卡住

**Comment by cxlanyagege** [comment]
mouse关了的话，看看clover加载磁盘属性选项里有没有开legancy，这个也有可能会和csm冲突

**Comment by cxlanyagege** [comment]
因为我在出国留学，所以今天才去超市买了根mdp的线，测试了下，问题依旧，而且有50%的几率唤醒后会直接五国重启

**Comment by SonglinYu1230** [comment]
我是直接设置的禁止睡眠

**Comment by cxlanyagege** [comment]
@yumumu 我也静止了睡眠，还在研究log

**Comment by SonglinYu1230** [comment]
> @yumumu 我也静止了睡眠，还在研究log

i9-8950HK, 日常使用会快很多吗？还有自带的90W电源对 i9-8950HK 来说是不是不够用？

**Comment by cxlanyagege** [comment]
> > @yumumu 我也静止了睡眠，还在研究log
> 
> i9-8950HK, 日常使用会快很多吗？还有自带的90W电源对 i9-8950HK 来说是不是不够用？

日常使用其实没多大差距，极限性能8950hk比8750h提升了10%-15%之间，自带的电源有点不够，双烤的时候会触发功耗墙，然后频率上下跳动，一般买i7款我觉得也差不多了，我纯粹是为了i9而买的i9，哈哈哈

**Comment by frankhefeng** [comment]
https://www.tonymacx86.com/threads/solved-hackintosh-freezes-while-playing-videos-on-safari-app-store.262218/page-2#post-1909803

照着这个帖子更新了两个 ktext，是否解决了偶现的视频卡住的问题有待观察，但惊喜的是开机之后双显示器 （一横一竖）的设置保留了，不用我再每次开机修正了。

**Comment by cxlanyagege** [comment]
> https://www.tonymacx86.com/threads/solved-hackintosh-freezes-while-playing-videos-on-safari-app-store.262218/page-2#post-1909803
> 
> 照着这个帖子更新了两个 ktext，是否解决了偶现的视频卡住的问题有待观察，但惊喜的是开机之后双显示器 （一横一竖）的设置保留了，不用我再每次开机修正了。

嗯，我的repo里把lilu和weg都更新了，因为显示器我只有一个所以多显示连接我不是很清楚，但是睡眠唤醒后软件崩溃safari无法播放视频依旧存在。而且很奇怪的是，我在翻log的时候看到了一条weg的报错。这几天有点忙，本来还想搞搞opencore的，现在看来没时间了

**Comment by SonglinYu1230** [comment]
睡眠问题，好像是 macOS 系统的问题，更新到 10.14.6 以后，我的就正常了。

**Comment by cxlanyagege** [comment]
> 睡眠问题，好像是 macOS 系统的问题，更新到 10.14.6 以后，我的就正常了。

我之前买好机器装的就是14.6，当时没注意，直接升级catalina beta了，然后发现睡眠有问题，双系统装了14.6，还是有问题，应该不是系统的问题

**Comment by SonglinYu1230** [comment]
> > 睡眠问题，好像是 macOS 系统的问题，更新到 10.14.6 以后，我的就正常了。
> 
> 我之前买好机器装的就是14.6，当时没注意，直接升级catalina beta了，然后发现睡眠有问题，双系统装了14.6，还是有问题，应该不是系统的问题

正常可能是偶然的，我的现在又不正常了。

**Comment by frankhefeng** [comment]
我升级 catalina，换成 @EngLearnsh 的EFI，再把 WhateverGreen 与 Lilu 都换成最新的，似乎发作几率低了些

**Comment by xiaominglei001** [comment]
> 我升级 catalina，换成 @EngLearnsh 的EFI，再把 WhateverGreen 与 Lilu 都换成最新的，似乎发作几率低了些

怎么升级10.15啊，我目前情况
```
系统10.14.4, cpu 8750h ，英睿达2666 8g ，ssd intel 760p ，无线网卡和蓝牙都是买时自带的，不用
```
目前用的EFI是这里这个，我想升级到10.15，直接升级不行，会出现一个圆圈加个斜杠，问下怎么办，用你提到的@EngLearnsh 的EFI替换我现在系统里的，然后在appstroe升级下系统就可以了吗
