### ISSUE TITLE
关于Catalina的问题

### ISSUE THREAD

**Issue by frankcui95** [kkzzhizhou/S200H_I7-8750H_Hackintosh#7]
这主机该怎么去适配10.15？

**Comment by frankcui95** [comment]
升级clover和驱动没改别的配置直接可用
![image](https://user-images.githubusercontent.com/11777709/66390984-770fcd00-e9fe-11e9-9209-7877d5dd1e4c.png)

**Comment by xiaominglei001** [comment]
怎么升级clover和驱动？我有bootdisk可以用来制作clover盘，剩下怎么做，能发个教程或需要的文件链接吗？

**Comment by frankhefeng** [comment]
下载这个： https://sourceforge.net/p/cloverefiboot/wiki/Configuration/
加载 EFI 分区，然后就可以替换了

**Comment by xiaominglei001** [comment]
我已升10.15，直接去这里看置顶回复里的最后信息，有方案，https://zhuanlan.zhihu.com/p/65263547
